apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    AWS/Lambda:
      - app
      - tenant
      - productId
      - mainProductId
  jobs:
    - type: AWS/Lambda
      enableMetricData: true
      regions:
        - eu-central-1
      searchTags:
        - key: app
          value: computation
      period: 300
      length: 300
      metrics:
        - name: Invocations
          statistics: [Sum]
        - name: Errors
          statistics: [Sum]
        - name: Throttles
          statistics: [Sum]
        - name: Duration
          statistics: [Average, Maximum, Minimum, p90]
        - name: Errors
          statistics: [Sum]
        - name: ConcurrentExecutions
          statistics: [Sum]